### ISSUE TITLE
SNP_Pos2polymarker_input.py showed KeyError: 'chr1A-494448626'

### ISSUE THREAD

**Issue by xuxuda** [pinbo/SNP_Primer_Pipeline#1]
![default](https://user-images.githubusercontent.com/36785671/51615892-e6728900-1f63-11e9-8a77-676fc93364ca.png)

Thanks for your share!This is a nice pipeline! I have a question now. Can you help me dissovle it ?

**Comment by pinbo** [comment]
Sorry for the late reply. I cannot figure it out without seeing your input file. If you do not mind, please attach all the input files in your command.

**Comment by xuxuda** [comment]
The previous question had been resolved but I met the other. If my sequences hit many targets in the genome, it will waste a lot of time to extract sequence from genome.  This likes a bug and need to be resolved. Thanks very much for your reply and this pipeline really help me a lot. Thanks again!


Best regards!


徐登安
中国农业科学院作物科学研究所
北京市海淀区中关村南大街12号
Tel:182-1037-1633
Dengan Xu
Institute of Crop Sciences
Chinese Academy of Agricultural Sciences
12 South Zhongguancun Street, Beijing 100081




On 3/17/2019 13:05，Junli Zhang<notifications@github.com> wrote：

Sorry for the late reply. I cannot figure it out without seeing your input file. If you do not mind, please attach all the input files in your command.

**Comment by homonecloco** [comment]
Hi, 
We where having the issue with long sequences  issue in earlier versions of polymarker. Now I have this script:
https://github.com/homonecloco/bioruby-polyploid-tools/blob/master/bin/vcfToPolyMarker.rb
That converts a VCF to the input in polymarker. You should be able to run it if you have the gem installed. 
Best, 
Ricardo.

**Comment by xuxuda** [comment]
Hi， 
I have got it. Thank you very much!


Best regards,


Dengan


徐登安
中国农业科学院作物科学研究所
北京市海淀区中关村南大街12号
Tel:182-1037-1633
Dengan Xu
Institute of Crop Sciences
Chinese Academy of Agricultural Sciences
12 South Zhongguancun Street, Beijing 100081




On 3/17/2019 19:33，Ricardo H. Ramírez-Gonzalez<notifications@github.com> wrote：

Hi,
We where having the issue with long sequences issue in earlier versions of polymarker. Now I have this script:
https://github.com/homonecloco/bioruby-polyploid-tools/blob/master/bin/vcfToPolyMarker.rb
That converts a VCF to the input in polymarker. You should be able to run it if you have the gem installed.
Best,
Ricardo.

**Comment by pinbo** [comment]
Hi Ricardo, Thanks for the information.

Hi Dengan, glad to hear that your first problem got fixed. For the 2nd one, I will try to fix it when I get time. For now, I just blast my input sequence manually to filter out these that have too many hits and only submit to the pipeline sequences that have reasonable numbers of hits.

Junli
