### ISSUE TITLE
chromosome name problem

### ISSUE THREAD

**Issue by ClayBirkett** [pinbo/SNP_Primer_Pipeline#2]
I got the following error when reference is using 1A,1B instead of chr1A
File "/opt/galaxy/tools/SNP_Primer_Pipeline/bin/SNP_Pos2polymarker_input.py", line 53, in __init__
    self.name = contig + ref_pos
TypeError: cannot concatenate 'str' and 'int' objects
I fixed using 
self.name = contig + str(ref_pos)

**Comment by pinbo** [comment]
Thanks, Clay. Bug fixed.
